In [16]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
import sqlite3
from sqlalchemy import create_engine, inspect
import pandas as pd
import json

### PostgresSQL Database

In [31]:
etl_project_db = "postgres:postgres@localhost:5432/ETL_Project_DB"
engine = create_engine(f'postgresql://{etl_project_db}')
# create a session
session = Session(engine)

### (E)TL Extract two datasets

In [34]:
# Extracted CSV Data
primary_df = pd.read_csv('us-2016-primary-results.csv', sep=';')
primary_df.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Vermont,VT,Sutton,95000197.0,Republican,John Kasich,20,0.227
1,Vermont,VT,Tunbridge,95000204.0,Republican,John Kasich,36,0.319
2,Vermont,VT,Weathersfield,95000220.0,Republican,Ted Cruz,46,0.111
3,Vermont,VT,Weston,95000228.0,Republican,John Kasich,32,0.471
4,Vermont,VT,Whiting,95000233.0,Republican,Ben Carson,0,0.000

In [33]:
# Extracted JSON data
with open('/Users/sahrmusa/Desktop/bootcamp/Homework/ETL-Project/2019_Results_backup.json') as json_file:
    data2 = json.load(json_file)

df = pd.DataFrame(data2['Andaman & Nicobar Islands'])
df.head()

,Constituency,O.S.N.,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes,Candidate Won
0,Andaman & Nicobar Islands,1,AYAN MANDAL,All India Trinamool Congress,1717,4,1721,0.83,loss
1,Andaman & Nicobar Islands,2,KULDEEP RAI SHARMA,Indian National Congress,95249,59,95308,45.98,loss
2,Andaman & Nicobar Islands,3,PRAKASH MINJ,Bahujan Samaj Party,2478,8,2486,1.20,loss
3,Andaman & Nicobar Islands,4,VISHAL JOLLY,Bharatiya Janata Party,93772,129,93901,45.30,loss
4,Andaman & Nicobar Islands,5,SANJAY MESHACK,Aam Aadmi Party,2837,2,2839,1.37,loss

### E(T)L Transform data

In [30]:
total_df = pd.DataFrame()
for key in data2.keys():
#     print(key)
    df = pd.DataFrame(data2[key])
    df['State'] = key
    total_df = total_df.append(df)
    
total_df.head()

,Constituency,O.S.N.,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% of Votes,Candidate Won,State
0,Andaman & Nicobar Islands,1,AYAN MANDAL,All India Trinamool Congress,1717,4,1721,0.83,loss,Andaman & Nicobar Islands
1,Andaman & Nicobar Islands,2,KULDEEP RAI SHARMA,Indian National Congress,95249,59,95308,45.98,loss,Andaman & Nicobar Islands
2,Andaman & Nicobar Islands,3,PRAKASH MINJ,Bahujan Samaj Party,2478,8,2486,1.20,loss,Andaman & Nicobar Islands
3,Andaman & Nicobar Islands,4,VISHAL JOLLY,Bharatiya Janata Party,93772,129,93901,45.30,loss,Andaman & Nicobar Islands
4,Andaman & Nicobar Islands,5,SANJAY MESHACK,Aam Aadmi Party,2837,2,2839,1.37,loss,Andaman & Nicobar Islands

In [29]:
primary_df.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Vermont,VT,Sutton,95000197.0,Republican,John Kasich,20,0.227
1,Vermont,VT,Tunbridge,95000204.0,Republican,John Kasich,36,0.319
2,Vermont,VT,Weathersfield,95000220.0,Republican,Ted Cruz,46,0.111
3,Vermont,VT,Weston,95000228.0,Republican,John Kasich,32,0.471
4,Vermont,VT,Whiting,95000233.0,Republican,Ben Carson,0,0.000